---
# defaults file for avinetworks.docker
docker_service_enabled: true
docker_config: {}
docker_edition: ce
docker_repo: docker
docker_channel: stable
docker_ee_version: 17.03
docker_options:
  api-cors-header: "{{ docker_api_cors_header | default(None) }}"
  authorization-plugins: "{{ docker_authorization_plugins | default(None) }}"
  bip: "{{ docker_bip | default(None) }}"
  bridge: "{{ docker_bridge | default(None) }}"
  cgroup-parent: "{{ docker_cgroup_parent | default(None) }}"
  cluster-store: "{{ docker_cluster_store | default(None) }}"
  cluster-store-opts: "{{ docker_cluster_store_opts | default(None) }}"
  cluster-advertise: "{{ docker_cluster_advertise | default(None) }}"
  debug: "{{ docker_debug | default(None) }}"
  default-gateway: "{{ docker_default_gateway | default(None) }}"
  default-gateway-v6: "{{ docker_default_gateway_v6 | default(None) }}"
  default-runtime: "{{ docker_default_runtime | default(None) }}"
  default-ulimits: "{{ docker_default_ulimits | default(None) }}"
  disable-legacy-registry: "{{ docker_disable_legacy_registry | default(None) }}"
  dns: "{{ docker_dns | default(None) }}"
  dns-opts: "{{ docker_dns_opts | default(None) }}"
  dns-search: "{{ docker_dns_search | default(None) }}"
  exec-opts: "{{ docker_exec_opts | default(None) }}"
  exec-root: "{{ docker_exec_root | default(None) }}"
  fixed-cidr: "{{ docker_fixed_cidr | default(None) }}"
  fixed-cidr-v6: "{{ docker_fixed_cidr_v6 | default(None) }}"
  graph: "{{ docker_graph | default(None) }}"
  group: "{{ docker_group | default(None) }}"
  hosts: "{{ docker_hosts | default(None) }}"
  icc: "{{ docker_icc | default(None) }}"
  insecure-registries: "{{ docker_insecure_registries | default(None) }}"
  ip: "{{ docker_ip | default(None) }}"
  iptables: "{{ docker_iptables | default(None) }}"
  ipv6: "{{ docker_ipv6 | default(None) }}"
  ip-forward: "{{ docker_ip_forward | default(None) }}"
  ip-masq: "{{ docker_ip_masq | default(None) }}"
  labels: "{{ docker_labels | default(None) }}"
  live-restore: "{{ docker_live_restore | default(None) }}"
  log-driver: "{{ docker_log_driver | default(None) }}"
  log-level: "{{ docker_log_level | default(None) }}"
  log-opts: "{{ docker_log_opts | default(None) }}"
  max-concurrent-downloads: "{{ docker_max_concurrent_downloads | default(None) }}"
  max-concurrent-uploads: "{{ docker_max_concurrent_uploads | default(None) }}"
  mtu: "{{ docker_mtu | default(None) }}"
  no-new-privileges: "{{ docker_no_new_privileges | default(None) }}"
  oom-score-adjust: "{{ docker_oom_score_adjust | default(None) }}"
  pidfile: "{{ docker_pidfile | default(None) }}"
  raw-logs: "{{ docker_raw_logs | default(None) }}"
  registry-mirrors: "{{ docker_registry_mirrors | default(None) }}"
  runtimes: "{{ docker_runtimes | default(None) }}"
  selinux-enabled: "{{ docker_selinux_enabled | default(None) }}"
  swarm-default-advertise-addr: "{{ docker_swarm_default_advertise_addr | default(None) }}"
  storage-driver: "{{ docker_storage_driver | default(None) }}"
  storage-opts: "{{ docker_storage_opts | default(None) }}"
  tls: "{{ docker_tls | default(None) }}"
  tlscacert: "{{ docker_tlscacert | default(None) }}"
  tlscert: "{{ docker_tlscert | default(None) }}"
  tlskey: "{{ docker_tlskey | default(None) }}"
  tlsverify: "{{ docker_tlsverify | default(None) }}"
  userland-proxy: "{{ docker_userland_proxy | default(None) }}"
  userns-remap: "{{ docker_userns_remap | default(None) }}"
